services:
  api-builder:
    container_name: api-builder
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app/
      - /app/node_modules
volumes:
  data:
