### Get all users
GET http://localhost:3000/users

### Create user
POST http://localhost:8000/api/v1/user/sign-up
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@example.com",
  "password": "123456789",
  "confirmPassword": "123456789"
}

### Sign in user
# @name signIn
POST http://localhost:8000/api/v1/user/sign-in
Content-Type: application/json

{
  "email": "gabriel@example.com",
  "password": "123456789"
}

### Get profile
GET http://localhost:8000/api/v1/user/profile
Content-Type: application/json
Authorization: Bearer {{signIn.response.body.data.token}}

### Refresh token
# @name refreshToken
POST http://localhost:8000/api/v1/user/refresh-token
Content-Type: application/json
Authorization: Bearer {{signIn.response.body.data.token}}

{
  "refreshToken": "{{signIn.response.body.data.refreshToken}}"
}