name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Test & Coverage
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env.test file
        run: |
          cat > .env.test <<EOF
          NODE_ENV=test
          POSTGRES_TEST_USER=${{ secrets.POSTGRES_TEST_USER }}
          POSTGRES_TEST_PASSWORD=${{ secrets.POSTGRES_TEST_PASSWORD }}
          POSTGRES_TEST_DB=${{ secrets.POSTGRES_TEST_DB }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REFRESH_JWT_SECRET=${{ secrets.REFRESH_JWT_SECRET }}
          SALT_ROUNDS=${{ secrets.SALT_ROUNDS }}
          API_PORT=${{ secrets.API_PORT }}
          EOF

      - name: Run tests with coverage
        run: npm run test:all:coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
          if-no-files-found: error

  docs:
    name: Build Swagger UI site
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Generate coverage badge (npm)
        run: npx coverage-badges-cli -o site/badges/coverage.svg coverage/lcov.info

      - name: Install swagger-ui-dist
        run: npm install swagger-ui-dist

      - name: Build Swagger UI site
        run: |
          mkdir -p site
          cp swagger.yml site/
          cp node_modules/swagger-ui-dist/swagger-ui.css site/
          cp node_modules/swagger-ui-dist/swagger-ui-bundle.js site/
          cat > site/index.html <<'EOF'
          <!doctype html>
          <html>
          <head>
            <meta charset="utf-8"/>
            <title>API Docs</title>
            <link rel="stylesheet" href="swagger-ui.css"/>
          </head>
          <body>
            <div id="swagger-ui"></div>
            <script src="swagger-ui-bundle.js"></script>
            <script>
              window.onload = () => {
                window.ui = SwaggerUIBundle({
                  url: './swagger.yml',
                  dom_id: '#swagger-ui'
                });
              };
            </script>
          </body>
          </html>
          EOF
          # Now include coverage:
          cp -r coverage/lcov-report site/coverage
          echo "Coverage copied to site/coverage"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
